class Jumper:

    def __init__(self):
        print('  ---  ')
        print(' /   \ ')
        print('  ---  ')
        print(' \   / ')
        print('  \ /  ')
        print('   0   ')
        print('  /|\  ')
        print('   |   ')
        print('  / \  ')
        print('')
        print('^^^^^^^')
        
    
    def drawing(self,failures):
        if failures == 0:
            print('\n  ---  ')
            print(' /   \ ')
            print('  ---  ')
            print(' \   / ')
            print('  \ /  ')
            print('   0   ')
            print('  /|\  ')
            print('   |   ')
            print('  / \  ')
            print('')
            print('^^^^^^^')
        elif failures == 1:
            print('\n /   \ ')
            print('  ---  ')
            print(' \   / ')
            print('  \ /  ')
            print('   0   ')
            print('  /|\  ')
            print('   |   ')
            print('  / \  ')
            print('')
            print('^^^^^^^')
        elif failures == 2:
            print('\n  ---  ')
            print(' \   / ')
            print('  \ /  ')
            print('   0   ')
            print('  /|\  ')
            print('   |   ')
            print('  / \  ')
            print('')
            print('^^^^^^^')
        elif failures == 3:
            print('\n \   / ')
            print('  \ /  ')
            print('   0   ')
            print('  /|\  ')
            print('   |   ')
            print('  / \  ')
            print('')
            print('^^^^^^^')
        elif failures == 4:
            print('\n  \ /  ')
            print('   0   ')
            print('  /|\  ')
            print('   |   ')
            print('  / \  ')
            print('')
            print('^^^^^^^')
        elif failures == 5:
            print('\n   X   ')
            print('  /|\  ')
            print('   |   ')
            print('  / \  ')
            print('')
            print('^^^^^^^')
